// ============================================================================
// Données démo pour le mode Demo de Powalyze
// ============================================================================

import type { CockpitData, Item } from './types-saas';

export const demoOrganisation: CockpitData = {
  organisation: {
    id: 'demo-org-1',
    name: 'Organisation Powalyze Demo',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  domains: [
    {
      id: 'demo-domain-1',
      organisation_id: 'demo-org-1',
      name: 'Gouvernance & Risques',
      description: 'Domaine principal de gouvernance',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  cockpit: {
    id: 'demo-cockpit-1',
    domain_id: 'demo-domain-1',
    name: 'Cockpit Exécutif',
    description: 'Vue d\'ensemble pour le COMEX',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  items: [
    // Risques
    {
      id: 'demo-item-1',
      cockpit_id: 'demo-cockpit-1',
      type: 'risk',
      title: 'Retard projet Cloud Migration',
      description: 'Le projet de migration cloud accuse 3 semaines de retard',
      status: 'critical',
      owner: 'Marie Dupont',
      due_date: '2026-02-15',
      score: 85,
      ai_comment: 'Risque critique nécessitant une action immédiate. Impact budgétaire estimé à 150K€.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-item-2',
      cockpit_id: 'demo-cockpit-1',
      type: 'risk',
      title: 'Conformité RGPD - Audit Q1',
      description: 'Préparation de l\'audit RGPD du premier trimestre',
      status: 'warning',
      owner: 'Jean Martin',
      due_date: '2026-03-31',
      score: 60,
      ai_comment: 'Attention requise sur la documentation des traitements de données.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-item-3',
      cockpit_id: 'demo-cockpit-1',
      type: 'risk',
      title: 'Turnover équipe IT',
      description: 'Taux de turnover élevé dans l\'équipe technique',
      status: 'warning',
      owner: 'Sophie Bernard',
      due_date: '2026-04-30',
      score: 55,
      ai_comment: 'Plan de rétention à mettre en place rapidement.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    
    // Décisions
    {
      id: 'demo-item-4',
      cockpit_id: 'demo-cockpit-1',
      type: 'decision',
      title: 'Choix fournisseur CRM',
      description: 'Décision sur le nouveau système CRM',
      status: 'critical',
      owner: 'Pierre Leroy',
      due_date: '2026-02-10',
      score: 90,
      ai_comment: 'Décision urgente requise. Comparatif Salesforce vs HubSpot finalisé.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-item-5',
      cockpit_id: 'demo-cockpit-1',
      type: 'decision',
      title: 'Budget formation 2026',
      description: 'Validation du budget formation annuel',
      status: 'ok',
      owner: 'Anne Petit',
      due_date: '2026-02-28',
      score: 30,
      ai_comment: 'En bonne voie, documentation complète.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    
    // KPIs
    {
      id: 'demo-item-6',
      cockpit_id: 'demo-cockpit-1',
      type: 'kpi',
      title: 'Taux de disponibilité système',
      description: 'Disponibilité des systèmes critiques',
      status: 'ok',
      owner: 'System',
      score: 99.8,
      ai_comment: 'Excellente performance, maintien des objectifs SLA.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-item-7',
      cockpit_id: 'demo-cockpit-1',
      type: 'kpi',
      title: 'Budget consommé Q1',
      description: 'Consommation budgétaire premier trimestre',
      status: 'warning',
      owner: 'Finance',
      score: 78,
      ai_comment: 'Légère dérive budgétaire (+8%), surveillance requise.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-item-8',
      cockpit_id: 'demo-cockpit-1',
      type: 'kpi',
      title: 'Satisfaction client NPS',
      description: 'Net Promoter Score',
      status: 'ok',
      owner: 'Customer Success',
      score: 72,
      ai_comment: 'Score satisfaisant, tendance positive (+5 points vs Q4).',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};
