// ============================================================
// POWALYZE V2 — MOCK DATA FOR DEMO MODE
// ============================================================

import type { Project, Risk, Decision, Resource } from './data-v2';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'demo-1',
    organization_id: 'demo-org',
    name: 'Refonte Plateforme E-commerce',
    description: 'Modernisation complète de la plateforme e-commerce avec architecture microservices',
    owner_id: 'demo-user-1',
    status: 'active',
    health: 'green',
    progress: 75,
    budget: 450000,
    deadline: '2026-06-30',
    starred: true,
    created_at: '2025-11-01T00:00:00Z',
  },
  {
    id: 'demo-2',
    organization_id: 'demo-org',
    name: 'Migration Cloud Azure',
    description: 'Migration de l\'infrastructure on-premise vers Azure Cloud',
    owner_id: 'demo-user-2',
    status: 'active',
    health: 'yellow',
    progress: 45,
    budget: 320000,
    deadline: '2026-08-31',
    starred: false,
    created_at: '2025-12-01T00:00:00Z',
  },
  {
    id: 'demo-3',
    organization_id: 'demo-org',
    name: 'Application Mobile Client',
    description: 'Développement application mobile iOS et Android pour les clients',
    owner_id: 'demo-user-1',
    status: 'active',
    health: 'green',
    progress: 60,
    budget: 280000,
    deadline: '2026-05-31',
    starred: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-4',
    organization_id: 'demo-org',
    name: 'Sécurité & Conformité RGPD',
    description: 'Mise en conformité RGPD et renforcement de la sécurité',
    owner_id: 'demo-user-3',
    status: 'active',
    health: 'red',
    progress: 30,
    budget: 150000,
    deadline: '2026-03-31',
    starred: false,
    created_at: '2025-10-15T00:00:00Z',
  },
  {
    id: 'demo-5',
    organization_id: 'demo-org',
    name: 'IA & Analyse Prédictive',
    description: 'Intégration de modèles IA pour l\'analyse prédictive des ventes',
    owner_id: 'demo-user-2',
    status: 'on-hold',
    health: 'yellow',
    progress: 15,
    budget: 380000,
    deadline: '2026-12-31',
    starred: false,
    created_at: '2025-11-15T00:00:00Z',
  },
  {
    id: 'demo-6',
    organization_id: 'demo-org',
    name: 'CRM Next Generation',
    description: 'Remplacement du CRM legacy par Salesforce',
    owner_id: 'demo-user-1',
    status: 'completed',
    health: 'green',
    progress: 100,
    budget: 220000,
    deadline: '2025-12-31',
    starred: false,
    created_at: '2025-06-01T00:00:00Z',
  },
];

export const MOCK_RISKS: Risk[] = [
  {
    id: 'risk-1',
    organization_id: 'demo-org',
    project_id: 'demo-1',
    title: 'Retard fournisseur infrastructure',
    description: 'Le fournisseur cloud annonce un retard de 3 semaines sur la livraison',
    level: 'high',
    probability: 0.7,
    impact: 0.8,
    status: 'open',
    owner_id: 'demo-user-1',
    mitigation_plan: 'Préparer un plan B avec fournisseur alternatif',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'risk-2',
    organization_id: 'demo-org',
    project_id: 'demo-4',
    title: 'Non-conformité RGPD détectée',
    description: 'Audit interne révèle des lacunes dans le traitement des données personnelles',
    level: 'critical',
    probability: 0.9,
    impact: 0.9,
    status: 'open',
    owner_id: 'demo-user-3',
    mitigation_plan: 'Plan d\'action urgent sous 30 jours',
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'risk-3',
    organization_id: 'demo-org',
    project_id: 'demo-2',
    title: 'Compétences Azure insuffisantes',
    description: 'L\'équipe manque d\'expertise Azure pour la migration',
    level: 'medium',
    probability: 0.6,
    impact: 0.6,
    status: 'mitigated',
    owner_id: 'demo-user-2',
    mitigation_plan: 'Formation Azure + recrutement d\'un expert cloud',
    created_at: '2025-12-10T00:00:00Z',
  },
];

export const MOCK_DECISIONS: Decision[] = [
  {
    id: 'decision-1',
    organization_id: 'demo-org',
    project_id: 'demo-1',
    title: 'Choix architecture microservices',
    description: 'Validation de l\'architecture microservices avec Kubernetes',
    committee: 'CODIR',
    decision_date: '2025-11-15',
    status: 'approved',
    owner_id: 'demo-user-1',
    impacts: [
      { type: 'budget', value: '+50k€' },
      { type: 'timeline', value: '+2 mois' },
      { type: 'resources', value: '+3 développeurs' },
    ],
    created_at: '2025-11-10T00:00:00Z',
  },
  {
    id: 'decision-2',
    organization_id: 'demo-org',
    project_id: 'demo-5',
    title: 'Gel du projet IA',
    description: 'Mise en pause du projet IA en attente de budget 2026',
    committee: 'COMEX',
    decision_date: '2026-01-10',
    status: 'approved',
    owner_id: 'demo-user-2',
    impacts: [
      { type: 'budget', value: '0€' },
      { type: 'timeline', value: 'Report Q2 2026' },
      { type: 'resources', value: 'Réaffectation équipe' },
    ],
    created_at: '2026-01-05T00:00:00Z',
  },
];

export const MOCK_RESOURCES: Resource[] = [
  {
    id: 'resource-1',
    organization_id: 'demo-org',
    name: 'Développeur Full-Stack',
    type: 'human',
    capacity: 40,
    unit: 'jours/mois',
    cost_per_unit: 600,
    created_at: '2025-10-01T00:00:00Z',
  },
  {
    id: 'resource-2',
    organization_id: 'demo-org',
    name: 'Architecte Cloud',
    type: 'human',
    capacity: 20,
    unit: 'jours/mois',
    cost_per_unit: 800,
    created_at: '2025-10-01T00:00:00Z',
  },
  {
    id: 'resource-3',
    organization_id: 'demo-org',
    name: 'Serveurs Azure',
    type: 'material',
    capacity: 100,
    unit: 'VM',
    cost_per_unit: 150,
    created_at: '2025-10-01T00:00:00Z',
  },
];
